In [55]:
import pandas as pd
import numpy as np
df=pd.read_csv('luis-daten.csv', sep=',',header = [0])
df_train = df.loc[df['Train'] == 1]
df_test = df.loc[df['Train'] == 1]
y_train = np.array([int(x>35) for x in df_train['PM10'].values.tolist()])
y_test = np.array([int(x>35) for x in df_test['PM10'].values.tolist()])
X_train = np.array(df_train.iloc[:,2:5].values)
X_test =  np.array(df_test.iloc[:,2:5].values)

[[ 1.98719200e+01  1.04809600e+01  1.08627280e+01]
 [ 1.95917680e+01  1.23649450e+01  1.27759430e+01]
 [ 2.99180700e+01  1.23827100e+01  1.50016290e+01]
 [ 3.00019840e+01  1.11955450e+01  1.40493960e+01]
 [ 3.27719400e+01  9.91663600e+00  1.29579740e+01]
 [ 4.15274850e+01  9.82110700e+00  1.26691160e+01]
 [ 4.94651800e+01  9.96416000e+00  1.22132640e+01]
 [ 2.68226380e+01  9.73058200e+00  1.14166880e+01]
 [ 3.03625160e+01  8.56014900e+00  1.17326010e+01]
 [ 3.23285560e+01  8.21521700e+00  1.06230030e+01]
 [ 1.33854410e+01  1.17484050e+01  1.15764150e+01]
 [ 1.40523500e+01  1.13919290e+01  1.15976230e+01]
 [ 2.39467140e+01  9.97151100e+00  1.05962760e+01]
 [ 2.03472560e+01  7.93810600e+00  9.21628100e+00]
 [ 2.11036100e+01  5.64939450e+00  9.03458900e+00]
 [ 1.68495390e+01  4.33919900e+00  7.38049750e+00]
 [ 1.46409000e+01  1.49266970e+00  4.50108530e+00]
 [ 1.80044420e+01  6.77165570e-01  3.54146860e+00]
 [ 2.23346310e+01 -1.56136470e+00  1.54697480e+00]
 [ 1.22495500e+01 -1.08926900e+